server:
  servlet:
    context-path: /
  port: 9009
logging:
  level:
    root: INFO
    com.xabe.redis: INFO
    org.springframework: INFO

redis:
  config:
    hostname: localhost
    port: 6379
    topic: payments