server:
  servlet:
    context-path: /
  port: 9080
logging:
  level:
    root: INFO
    com.xabe.spring.cloud.stream: INFO
    org.springframework.cloud.stream: INFO

redis:
  config:
    hostname: localhost
    port: 6379
    topic: payments